/* eslint-disable camelcase */

import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { ThemeProvider } from 'next-themes'
import { AuthProvider } from '@/context/AuthContext'
import './globals.css'
import { TanstackProvider } from './providers'
import { ServerDataProvider } from '@/context/ServerDataContext'

import { AppSidebar } from '@/components/AppSideBar'
import { BreadcrumbNav } from '@/components/BreadCrumbNav'
import { ThemeToggle } from '@/components/Theme'
import { Separator } from '@/components/ui/separator'
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from '@/components/ui/sidebar'
import { getUserServerData } from '@/lib/server/data/user/getUserServerData'
import {
  getSkinsServerData,
  getAllSkinsServerData,
} from '@/lib/server/data/skins/getSkinsServerData'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const [userData, skinsData, allSkinsData] = await Promise.all([
    getUserServerData(),
    getSkinsServerData(),
    getAllSkinsServerData(),
  ])

  const serverData = {
    user: userData.user,
    profile: userData.profile,
    skinTypes: skinsData.skinTypes,
    skins: allSkinsData.skins,
  }

  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TanstackProvider>
          <ThemeProvider attribute="class" defaultTheme="light">
            <AuthProvider>
              <ServerDataProvider data={serverData}>
                <SidebarProvider key="sidebar-provider">
                  <AppSidebar serverUserData={serverData} />
                  <SidebarInset>
                    <header className="flex h-16 shrink-0 items-center justify-between gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12">
                      <div className="flex items-center gap-2 px-4">
                        <SidebarTrigger className="-ml-1" />
                        <Separator
                          orientation="vertical"
                          className="mr-2 h-4"
                        />
                        <BreadcrumbNav />
                      </div>
                      <div className="flex items-center gap-2 px-4">
                        <ThemeToggle />
                      </div>
                    </header>
                    {children}
                  </SidebarInset>
                </SidebarProvider>
              </ServerDataProvider>
            </AuthProvider>
          </ThemeProvider>
        </TanstackProvider>
      </body>
    </html>
  )
}
